version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_projectmanager
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projectmanager_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
